server:
  address: "0.0.0.0:9000"
  secret: "change-me-to-a-random-secret"
  cookieSecure: false

database:
  dsn: "host=localhost port=5432 user=postgres password=postgres dbname=niubility sslmode=disable"

sso:
  host: http://bo-staging-sso-internal.jfcs-k8s-qa1.qiniu.io
  clientID: niubility
  secret: BCR0nzlmnvwWIjIxc8Ij0MfOTfc5Udh6

wechat:
  corp_id: "your-corp-id"
  app_agentid: 0
  app_secret: "your-app-secret"
